# Site-wide settings
title: 月田意意网站
email: jakehary18@gmail.com
author:
  name: yeutian
  email: jakehary18@gmail.com
description: >-
  欢迎来到我的第一个精美网页！这是我通过 GitHub Pages 搭建的自留地。

# Build settings
# 这里使用远程主题，确保你的网页能正常显示皮肤
remote_theme: jekyll/minima@d4d779a

# 启用必要的插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima 皮肤设置
minima:
  skin: auto
  show_excerpts: true
  social_links:
    - title: 我的 GitHub
      icon: github
      url: "https://github.com/jakehary888"
